baseURL = "http://example.org/"
languageCode = "en-us"
title = "Just A Card - Hugo"
theme = "just-a-card"

[author]
  name = "John Doe"
  title = "Software Engineer"
  location = "Somewhere in the world"
  company = "Company"
  companyUrl = "#"
  intro = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non elementum ipsum. Integer convallis iaculis felis, a pellentesque leo accumsan vitae. Vestibulum eu ullamcorper purus. Maecenas sollicitudin, turpis vitae ullamcorper cursus, purus quam sagittis nisl, ut laoreet turpis justo malesuada leo."
  profile_image = "images/profile.jpeg"

[params]
  primary_color = "#ffe9a0"
  secondary_color = "#4789d8"
  google_font = "Overpass"

  [[params.links]]
    icon = "link"
    name = "E-mail"
    url = "mailto:#"
  [[params.links]]
    icon = "github"
    name = "Github"
    url = "https://github.com/#"
  [[params.links]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/#"
  [[params.links]]
    icon = "file-text"
    name = "Hire me!"
    url = "#"